# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: postgres:12.3
    restart: always
    ports:
      - 5432:5432/tcp
    environment:
        POSTGRES_PASSWORD: modere
    volumes:
        - ${WORKSPACE}:/var/lib/postgresql/modere:rw